
version: "3.8"

services:
  postgres:
    container_name: quiz_db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: quiz_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200
    read_only: false
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh
    links:
      - mailcatcher

  app-migrations:
    container_name: quiz_app-migrations
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    read_only: false
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/setup-db.sh


volumes:
  postgres-data:
  redis-data:
  app:

networks:
  app: