name: "RSpec Tests and Simplecov coverage"
on:
  pull_request:
    branches: [ "main" ]

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://user:password@localhost:5432/quiz_test"
  ELASTICSEARCH_URL: 'http://localhost:9200'

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: quiz_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: |
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec
